#!/usr/bin/env python3
"""Generate LICENSES.txt, THIRD_PARTY_LICENSES.txt, and CREDITS.txt."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "licenses" / "manifest.yaml"
OUTPUT_DIR = REPO_ROOT / "vendor" / "mozc" / "src" / "data" / "installer"
GENERATED_DIR = REPO_ROOT / "generated"


def load_manifest() -> list[dict]:
    """Parse the simple YAML manifest without external dependencies."""
    components: list[dict] = []
    current: dict[str, str] = {}
    in_components = False

    with open(MANIFEST, encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line == "components:":
                in_components = True
                continue
            if not in_components:
                continue
            if line.startswith("- name:"):
                if current:
                    components.append(current)
                current = {"name": line.split(":", 1)[1].strip()}
                continue
            if line.startswith("- ") and "name:" in line:
                if current:
                    components.append(current)
                current = {"name": line.split("name:", 1)[1].strip()}
                continue
            if ":" in line and current is not None:
                key, value = line.split(":", 1)
                current[key.strip()] = value.strip()

    if current:
        components.append(current)
    return components


def read_license_text(path: Path) -> str:
    full_path = REPO_ROOT / path
    if not full_path.exists():
        raise FileNotFoundError(f"Missing license text: {full_path}")
    return full_path.read_text(encoding="utf-8").strip()


def generate_licenses_txt(components: list[dict]) -> str:
    primary = [
        "Mozc UT Privacy Edition - License Summary",
        "=" * 60,
        "",
        "This distribution combines:",
        "",
        "1. Mozc (BSD-3-Clause) - Japanese IME engine by Google",
        "2. merge-ut-dictionaries (Apache-2.0) - UT dictionary merge tools",
        "3. Combined UT dictionary data (multiple licenses; see CREDITS.txt)",
        "4. Third-party libraries (see THIRD_PARTY_LICENSES.txt)",
        "",
        "This project is an unofficial community build. It is not affiliated",
        "with Google LLC or the official Mozc project.",
        "",
    ]
    for component in components:
        if component["name"] in (
            "Mozc",
            "merge-ut-dictionaries",
            "Mozc UT Privacy Edition Project",
        ):
            primary.extend([
                f"## {component['name']}",
                f"SPDX: {component['spdx']}",
                f"Copyright: {component['copyright']}",
                f"Source: {component['source_url']}",
                "",
            ])
    return "\n".join(primary)


def generate_third_party_txt(components: list[dict]) -> str:
    sections = ["Third-Party Licenses", "=" * 60, ""]
    seen_files: set[str] = set()

    for component in components:
        license_file = component["license_file"]
        if license_file in seen_files:
            continue
        seen_files.add(license_file)
        text = read_license_text(license_file)
        sections.extend([
            "-" * 60,
            f"Component: {component['name']}",
            f"SPDX: {component['spdx']}",
            f"Copyright: {component['copyright']}",
            f"Source: {component['source_url']}",
            f"License file: {license_file}",
            "-" * 60,
            "",
            text,
            "",
        ])
    return "\n".join(sections)


def generate_credits_txt(components: list[dict]) -> str:
    lines = [
        "Credits and Attributions",
        "=" * 60,
        "",
        "Mozc UT Privacy Edition includes the following components:",
        "",
    ]
    for component in components:
        lines.append(
            f"- {component['name']}: {component['copyright']} "
            f"({component['spdx']}) - {component['source_url']}"
        )
    lines.extend([
        "",
        "UT dictionary data is generated by merge-ut-dictionaries from",
        "community-maintained supplemental dictionary repositories.",
        "",
        "Japanese Wikipedia title data (CC BY-SA) is used during the build",
        "process only to estimate word popularity for cost tuning.",
        "",
    ])
    return "\n".join(lines) + "\n"


def check_manifest(components: list[dict]) -> list[str]:
    errors = []
    for component in components:
        path = REPO_ROOT / component["license_file"]
        if not path.exists():
            errors.append(f"Missing license file for {component['name']}: {path}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate license bundle files.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify manifest entries without writing output files.",
    )
    args = parser.parse_args()

    components = load_manifest()
    errors = check_manifest(components)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if args.check:
        print("License manifest check passed.")
        return 0

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    outputs = {
        "LICENSES.txt": generate_licenses_txt(components),
        "THIRD_PARTY_LICENSES.txt": generate_third_party_txt(components),
        "CREDITS.txt": generate_credits_txt(components),
    }

    for name, content in outputs.items():
        target = OUTPUT_DIR / name
        target.write_text(content + "\n", encoding="utf-8")
        (GENERATED_DIR / name).write_text(content + "\n", encoding="utf-8")
        print(f"Wrote {target}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
